/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GameArenaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REWARD_AMOUNT"
      | "TRAINING_DURATION"
      | "activeSessions"
      | "aqToken"
      | "endTraining"
      | "heroNft"
      | "owner"
      | "renounceOwnership"
      | "startTraining"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "TrainingEnded"
      | "TrainingStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "REWARD_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRAINING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeSessions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "aqToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "endTraining",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "heroNft", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startTraining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "REWARD_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRAINING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aqToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "endTraining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "heroNft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startTraining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrainingEndedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenId: BigNumberish,
    reward: BigNumberish,
    newLevel: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenId: bigint,
    reward: bigint,
    newLevel: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenId: bigint;
    reward: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrainingStartedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenId: BigNumberish,
    startTime: BigNumberish
  ];
  export type OutputTuple = [user: string, tokenId: bigint, startTime: bigint];
  export interface OutputObject {
    user: string;
    tokenId: bigint;
    startTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameArena extends BaseContract {
  connect(runner?: ContractRunner | null): GameArena;
  waitForDeployment(): Promise<this>;

  interface: GameArenaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REWARD_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  TRAINING_DURATION: TypedContractMethod<[], [bigint], "view">;

  activeSessions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        tokenId: bigint;
        startTime: bigint;
        isTraining: boolean;
      }
    ],
    "view"
  >;

  aqToken: TypedContractMethod<[], [string], "view">;

  endTraining: TypedContractMethod<[], [void], "nonpayable">;

  heroNft: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  startTraining: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REWARD_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TRAINING_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeSessions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean] & {
        tokenId: bigint;
        startTime: bigint;
        isTraining: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "aqToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "endTraining"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "heroNft"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startTraining"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TrainingEnded"
  ): TypedContractEvent<
    TrainingEndedEvent.InputTuple,
    TrainingEndedEvent.OutputTuple,
    TrainingEndedEvent.OutputObject
  >;
  getEvent(
    key: "TrainingStarted"
  ): TypedContractEvent<
    TrainingStartedEvent.InputTuple,
    TrainingStartedEvent.OutputTuple,
    TrainingStartedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TrainingEnded(address,uint256,uint256,uint256)": TypedContractEvent<
      TrainingEndedEvent.InputTuple,
      TrainingEndedEvent.OutputTuple,
      TrainingEndedEvent.OutputObject
    >;
    TrainingEnded: TypedContractEvent<
      TrainingEndedEvent.InputTuple,
      TrainingEndedEvent.OutputTuple,
      TrainingEndedEvent.OutputObject
    >;

    "TrainingStarted(address,uint256,uint256)": TypedContractEvent<
      TrainingStartedEvent.InputTuple,
      TrainingStartedEvent.OutputTuple,
      TrainingStartedEvent.OutputObject
    >;
    TrainingStarted: TypedContractEvent<
      TrainingStartedEvent.InputTuple,
      TrainingStartedEvent.OutputTuple,
      TrainingStartedEvent.OutputObject
    >;
  };
}
