/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AQToken } from "./AQToken";
export type { GameArena } from "./GameArena";
export type { HeroNFT } from "./HeroNFT";
